namespace: your_org
name: aap_ha_patroni
version: 1.0.0
readme: README.md
authors:
  - "Your Name"
description: AAP 2.6 with Patroni/etcd PostgreSQL HA. No PAH or eDA HA.
license:
  - GPL-3.0-or-later
dependencies:
  community.postgresql: ">=3.4.0"
